"use strict";
// This file will be generated by running: pnpm supabase:types
// Make sure to set SUPABASE_PROJECT_ID in your environment
Object.defineProperty(exports, "__esModule", { value: true });
